version: '3.9'

services:
  notificator:
    build:
      context: ./TelegramBot
      dockerfile: Dockerfile
    container_name: notificator
    command: sh -c "python main.py"
    networks:
      - default

