version: '3.9'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "8000:8000"
    command: "./main"

  telegram_bot:
    build:
      context: ./TelegramBot
      dockerfile: Dockerfile
    container_name: telegram_bot
    ports:
      - "3000:3000"
    command: sh -c "python main.py"

  notificator:
    build:
      context: ./TelegramBot
      dockerfile: Dockerfile
    container_name: notificator
    command: sh -c "python main.py"

  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - postgres_storage:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    depends_on:
      - postgres
    container_name: keycloak
    env_file:
      - ./.env
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
      - --import-realm
    ports:
      - "8080:8080"

volumes:
  postgres_storage:

networks:
  default:
