// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import (
	models "Notifications/internal/models"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// UseCase is an autogenerated mock type for the UseCase type
type UseCase struct {
	mock.Mock
}

// AddNotificationToAccount provides a mock function with given fields: ctx, notificationId, accountId
func (_m *UseCase) AddNotificationToAccount(ctx context.Context, notificationId uuid.UUID, accountId []uuid.UUID) error {
	ret := _m.Called(ctx, notificationId, accountId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []uuid.UUID) error); ok {
		r0 = rf(ctx, notificationId, accountId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AllNotifications provides a mock function with given fields: ctx
func (_m *UseCase) AllNotifications(ctx context.Context) ([]models.Notification, error) {
	ret := _m.Called(ctx)

	var r0 []models.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.Notification, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.Notification); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateNotification provides a mock function with given fields: ctx, _a1
func (_m *UseCase) CreateNotification(ctx context.Context, _a1 models.Notification) error {
	ret := _m.Called(ctx, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Notification) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteNotification provides a mock function with given fields: ctx, _a1
func (_m *UseCase) DeleteNotification(ctx context.Context, _a1 string) error {
	ret := _m.Called(ctx, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteNotificationFromAccount provides a mock function with given fields: ctx, notificationId, accountId
func (_m *UseCase) DeleteNotificationFromAccount(ctx context.Context, notificationId uuid.UUID, accountId uuid.UUID) error {
	ret := _m.Called(ctx, notificationId, accountId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, notificationId, accountId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NotificationById provides a mock function with given fields: ctx, _a1
func (_m *UseCase) NotificationById(ctx context.Context, _a1 string) (*models.Notification, error) {
	ret := _m.Called(ctx, _a1)

	var r0 *models.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Notification, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Notification); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NotificationsByUser provides a mock function with given fields: ctx, _a1
func (_m *UseCase) NotificationsByUser(ctx context.Context, _a1 string) ([]models.Notification, error) {
	ret := _m.Called(ctx, _a1)

	var r0 []models.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]models.Notification, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []models.Notification); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateNotifications provides a mock function with given fields: ctx, _a1, _a2
func (_m *UseCase) UpdateNotifications(ctx context.Context, _a1 string, _a2 models.UpdatedNotification) (*models.UpdatedNotification, error) {
	ret := _m.Called(ctx, _a1, _a2)

	var r0 *models.UpdatedNotification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, models.UpdatedNotification) (*models.UpdatedNotification, error)); ok {
		return rf(ctx, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, models.UpdatedNotification) *models.UpdatedNotification); ok {
		r0 = rf(ctx, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UpdatedNotification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, models.UpdatedNotification) error); ok {
		r1 = rf(ctx, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUseCase creates a new instance of UseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UseCase {
	mock := &UseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
